### ISSUE TITLE
Multiple threads in LinearOpMode

### ISSUE THREAD

**Issue by pjtnt11** [ftctechnh/ftc_app#100]
Is there a way to create multiple threads in a LinearOpMode to allow me to do things like constantly update sensor variables in the back ground or add a timer to automatically stop the program?

**Comment by KingofGamesYami** [comment]
http://ftcforum.usfirst.org/showthread.php?5788-Integrating-Java-Threads-with-ftc_app-new-control-system-model-can-it-be-done

**Comment by cmacfarl** [comment]
Discussed in forums.
