### ISSUE TITLE
Color Sensor starts up with LED on instead of off

### ISSUE THREAD

**Issue by ThomasDoylend** [ftctechnh/ftc_app#101]

**Comment by magneticflux-** [comment]
Is this an issue?

**Comment by ThomasDoylend** [comment]
I'm not sure. It's probably very low-priority, just figured I'd let you
know. More info is always better than less.

**Comment by eukota** [comment]
This is the default for the chip. If you plug it in without any data connected, it will turn the LED on. I find it incredibly useful. It lets you know the sensor is getting power.

**Comment by ThomasDoylend** [comment]
OK. Good to know. Thanks for your time.
