### ISSUE TITLE
NXT Color Sensor

### ISSUE THREAD

**Issue by wilco375** [ftctechnh/ftc_app#103]
The Lego NXT Color Sensor is not working for us. Will this be supported in the future?

**Comment by calebsander** [comment]
There doesn't seem to be any plan to support it. It uses a combination of the analog and digital connections, so it is a bit weird to work with. The sensor is also not of fantastic quality, so I would recommend looking into another color sensor.

**Comment by calebsander** [comment]
Can this be closed?

**Comment by Ace314159** [comment]
My team has tried to use the NXT Color Sensor, and it *does* work. However, the quality was good as @calebsander stated.

**Comment by wilco375** [comment]
Closed it
