### ISSUE TITLE
Telemetry is missing from documentation

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#127]
The JavaDocs seem to leave out everything in the `com.qualcomm.robotcore.robocol` package, most notably the `Telemetry` class.

**Comment by calebsander** [comment]
Still an issue in yesterday's release

**Comment by ftctechnh** [comment]
Thanks Caleb.  Will address this in next release.

**Comment by cmacfarl** [comment]
Added in upcoming release.
