### ISSUE TITLE
Legacy Ultrasonic Sensor Unit of Measure

### ISSUE THREAD

**Issue by pjtnt11** [ftctechnh/ftc_app#130]
I was wondering if anyone knew the unit of measure that the Ultrasonic sensor returned when you used the function "getUltrasonicLevel()." I assumed that it was cm but I measured and that doesn't look to be true.

**Comment by gvb** [comment]
The distance is in centimeters, but it has limited accuracy.

This article gives very good background information: [The Ultrasonic Sensor](https://nxttime.wordpress.com/2012/09/12/the-ultrasonic-sensor/)

**Comment by cmacfarl** [comment]
Answered.  by gvb.
