### ISSUE TITLE
OpMode telemetry can be displayed before the OpMode starts

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#132]
Steps to reproduce:

1. Initialize and start an OpMode that writes to telemetry during `loop()` only
2. (Optional) Stop the OpMode
3. Select another OpMode from the menu
4. Select the first OpMode again
5. Initialize it
6. Notice that the last telemetry data appears on the screen

This can be confusing because it appears as though the OpMode is running yet the telemetry data is from a previous run and doesn't update.

Screenshot:
<img src="https://cloud.githubusercontent.com/assets/4256376/12539682/4e8b371a-c2c6-11e5-93cb-dc9029fdd4b2.png" width=200 />
Here, `BNO055` is an OpMode that only displays that information during `loop()`, so the bottom of the screen should be empty during the `init()` phase.

**Comment by lukethecoder64** [comment]
Ooh, good catch!

Luke
     __
    /   /
   /   /
  /   /
 /   /______
/_________/

**Comment by calebsander** [comment]
Seems fixed in 2.0.
