### ISSUE TITLE
It is misleading to have HiTechnicNxtServoController.getServoPosition(int channel) return 0 and getPwmStatus() return DISBALED

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#136]
If this is not supported, it should throw an exception rather than silently return 0.0, which looks like a legal value.

**Comment by lukethecoder64** [comment]
Yes, but doesn't that mean that every time we read a servo we have to use try/catch?

**Comment by calebsander** [comment]
Not if you made it throw a `RuntimeException`. If you forgot that it was on a HiTechnic controller, then it would throw the error once and you would change the code to stop calling it. If it was on a Modern Robotics controller, it wouldn't ever throw an exception.

**Comment by magneticflux-** [comment]
The correct exception to be thrown, inline with default libraries and the [gyro](https://htmlpreview.github.io/?https://raw.githubusercontent.com/ftctechnh/ftc_app/master/doc/javadoc/com/qualcomm/robotcore/hardware/GyroSensor.html#rawZ()) code, would be ```UnsupportedOperationException```, which is a ```RuntimeException```.

**Comment by calebsander** [comment]
Yes, I meant that throwing any sort of `RuntimeException` would be sufficient to not require a try-catch statement every time the method is called.

**Comment by lukethecoder64** [comment]
Thanks for the clarification, @calebsander and @magneticflux- . Yes, I agree that an exception should be thrown. +1.

**Comment by calebsander** [comment]
There is a similar issue with `getPwmStatus()`. It always returns `PwmStatus.DISABLED`.

**Comment by calebsander** [comment]
Still an issue in yesterday's release

**Comment by calebsander** [comment]
Seems fixed in 2.0.
