### ISSUE TITLE
Continuous Rotation servos should be treated differently from normal servos

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#137]
There are several points where I think the SDK would benefit from having a clear split between CR and positional servos:
- They should use `setPower()` with `DcMotor`-like values instead of `setPosition()` to make their usage more intuitive
- When no `OpMode` is running, they should be stopped before PWM is disabled, because otherwise they can do serious damage and disqualify teams
- They should not be included in the `HardwareMap.servo` `DeviceMapping` because iterating over it and doing the same thing for each servo would cause CR servos and normal servos to act differently
- To these ends, this distinction should exist in the configuration file so it is harder for a team to confuse the two sorts of devices

**Comment by JacobAMason** [comment]
I think it'd be good to make the two distinct as well. We came across the same thing and I know this would be a relatively easy fix. Until one is committed, it's not too hard to write a wrapper. We plan on doing that soon, so when we do, I'll edit this comment and link it here.

**Comment by lukethecoder64** [comment]
+1. This should be obvious.

Luke
     __
    /   /
   /   /
  /   /
 /   /______
/_________/

**Comment by JacobAMason** [comment]
Here's an easy sample FTC3486/FTCRC_Extensions@62491e2006eb88b22fa8f0f719cf28666afa8c65

**Comment by calebsander** [comment]
Fixed in 2.0.
