### ISSUE TITLE
.gitignore is set to ignore itself

### ISSUE THREAD

**Issue by JacobAMason** [ftctechnh/ftc_app#14]
I'm not even sure what happened here, but this is probably wrong.
https://github.com/ftctechnh/ftc_app/blob/b4b71b2949/.gitignore#L27-29

**Comment by NoahAndrews** [comment]
This has been fixed in the latest commit.

**Comment by JacobAMason** [comment]
Fixed in 4e2390039f7b9c48b00af3f63b43516058365b7f
