### ISSUE TITLE
I2cDeviceSynchImpl Reads Twice

### ISSUE THREAD

**Issue by luciengaitskell** [ftctechnh/ftc_app#163]
I have been trying to use the `I2cDeviceSyncImpl` class with various i2c devices and I have noticed that it is doing the read transactions twice (I looked at the Data and the Clock using an oscilloscope). Is there a reason for this?

**Comment by rgatkinson** [comment]
Do you have an example OpMode that exhibits the behavior? Or perhaps other details?

**Comment by luciengaitskell** [comment]
Here:
[LidarLiteReadTest.java.zip](https://github.com/ftctechnh/ftc_app/files/190544/LidarLiteReadTest.java.zip)

**Comment by rgatkinson** [comment]
Thanks for this Lucien. Hopefully this will be fixed in the next release.

**Comment by cmacfarl** [comment]
Fixed in new beta.
