### ISSUE TITLE
FTC Technology Forum down?

### ISSUE THREAD

**Issue by AlecHub** [ftctechnh/ftc_app#164]
I get the following error when trying to access http://ftcforum.usfirst.org/forumdisplay.php?156-FTC-Technology:

> **Warning:** Illegal string offset 'name' in **[path]/includes/functions.php** on line **6988**
> Unable to add cookies, header already sent.
> File: /homepages/4/d174712211/htdocs/public_html/ftcforum/includes/class_core.php
> Line: 5615

Anyone else getting this error?

**Comment by rschildge** [comment]
Me too.

**Comment by magneticflux-** [comment]
@AlecHub I am as well. Windows 8.1 64x, Chrome 49.0.2623.110

**Comment by lukethecoder64** [comment]
Same here. Firefox.

**Comment by AlecHub** [comment]
I am able to access the technology forum only if I login to http://ftcforum.usfirst.org.

**Workaround:** login to http://ftcforum.usfirst.org

**Comment by AlecHub** [comment]
It is no longer necessary to login to access the forum, so the issue appears to be resolved.

**Comment by calebsander** [comment]
Can this be closed?

**Comment by lukethecoder64** [comment]
Could this be closed?
