### ISSUE TITLE
Dependencies should be handled by Gradle/Maven

### ISSUE THREAD

**Issue by nrizzio** [ftctechnh/ftc_app#165]
Instead of including the FTC libraries as `.aar` files into this repository, [they should be uploaded as artifacts to the Maven Central Repository.](https://maven.apache.org/guides/mini/guide-central-repository-upload.html)

[`compile(name: 'RobotCore-release', ext: 'aar')`](https://github.com/ftctechnh/ftc_app/blob/83d998b9e9937e51b96acae151aa10b993ca1a83/FtcRobotController/build.gradle#L41-L46) would become
`compile 'com.qualcomm.ftcrobotcontroller.robotcore-release:1.7'`. This same pattern would apply to all of the other libraries as well.

That way, whenever a new version of the libraries are released, the source `.aar`s would be uploaded to Maven, while the only change needed within this repository would be to increment the version number of the corresponding library dependency in [`build.gradle`](https://github.com/ftctechnh/ftc_app/blob/83d998b9e9937e51b96acae151aa10b993ca1a83/FtcRobotController/build.gradle#L41-L46). The [`libs`](https://github.com/ftctechnh/ftc_app/tree/83d998b9e9937e51b96acae151aa10b993ca1a83/FtcRobotController/libs) folder would no longer be polluted with raw binaries that change all of the time.

When it reads `compile 'com.qualcomm.ftcrobotcontroller.robotcore-release:1.7'`, Gradle will automatically search for and download the appropriate libraries from Maven and allow Android Studio to build the app.

**Comment by cmacfarl** [comment]
Thank you for your suggestion.  

However, the SDK has a requirement that it must build in its entirety without an internet connection.  To which I hear you exclaiming, "But you must have an internet connection to acquire it in the first place."  Yes, and perhaps no.  Some teams acquire and/or share the SDK from thumb drives.   Some of which were acquired using GitHub's compressed archive download feature and hence contain a completely vanilla copy of the repository.  These teams are also most likely not to have internet connectivity when first building the apk.

Therefore all dependent libraries will remain packaged with the SDK.
