### ISSUE TITLE
Android Studio 2.0 Support

### ISSUE THREAD

**Issue by 2000andrewbowen** [ftctechnh/ftc_app#178]
I downloaded the sdk on 7/26/2016 and tried to run it, but I got this error: 

Error:Execution failed for task ':FtcRobotController:compileDebugJavaWithJavac'.
> java.io.FileNotFoundException: C:\Users\*\*\*\*\ftc_app-master\FtcRobotController\libs\android-support-v4.jar (The system cannot find the file specified)

I was able to fix it, but it took me an hour to found how to fix the error at this forum [post](http://ftcforum.usfirst.org/showthread.php?6738-Android-Studio-2-0-and-SDK-Release-16-03-09-Signed-Gradle) . 

Please change fix this.

**Comment by JacobAMason** [comment]
This is already being addressed at #176

**Comment by cmacfarl** [comment]
Fixed in SDK 2.0 (in the beta branch currently)
