### ISSUE TITLE
cloning the TeamCode Module instructions in TeamCode readme.md

### ISSUE THREAD

**Issue by cev136** [ftctechnh/ftc_app#185]
There are some typos and hazy references in the "cloning the teamcode module" instructions in ftc_app\TeamCode\src\main\java\org\firstinspires\ftc\teamcode readme.md:

3) "src/main/java/org/firstinspires/teamcode" should be "src/main/java/org/firstinspires/ftc/teamcode"
4) 'team0417 folder' should be '"Team0417/src/main" folder'
5) "Gradle Scripts/settings.gradle" should be "ftc_app/settings.gradle"

**Comment by gearsincorg** [comment]
Thanks.    Yes, that section was based on a possible use-model, and not completely flushed out.   Your corrections are on point.

Phil.

**Comment by gearsincorg** [comment]
Incorporated in Master 2.1.
