### ISSUE TITLE
Vuforia target config XML references nonexistent file

### ISSUE THREAD

**Issue by AidanBoyer** [ftctechnh/ftc_app#190]
The Vuforia target config file, ftc_app/FtcRobotController/src/main/assets/FTC_2016-17.xml references "qcar_config.xsd", which leads to an error. This file was expected to be in Program Files/Java/jdk1.8.0_101/jre/bin but is not there. This is also the case with the StonesAndChips.xml file.

**Comment by rgatkinson** [comment]
This error exhibited by Android Studio is innocuous. It applies to supporting editing these files with an XML Schema Design language-aware editor, not to their runtime interpretation. The files function correctly for their intended purpose with this XSD schema reference indicator pointing to an unavailable location.

These files are as they came out of the Vuforia Target Manager tool; it seemed most appropriate to use them verbatim.
