### ISSUE TITLE
missing android-support-v4.jar

### ISSUE THREAD

**Issue by pbaier** [ftctechnh/ftc_app#194]
Hello,

When trying to upload code from Android Studio to our Robot Controller phone, we are always getting an error that we are missing android-support-v4.jar. We have messed around with our repositories and it seems like we are all set, but there must be something we are missing. Has anyone had this issue that can help?

Thanks

**Comment by lukethecoder64** [comment]
See: https://github.com/ftctechnh/ftc_app/pull/176/files

**Comment by JacobAMason** [comment]
You may alternatively remove that line completely. I don't think it's in the new code, anyway.

**Comment by pbaier** [comment]
Worked! Thank you!
