### ISSUE TITLE
Enable GitHub Pages so that documentation can be viewed online

### ISSUE THREAD

**Issue by nrizzio** [ftctechnh/ftc_app#195]
All that is required is for @ftctechnh to [enable GitHub Pages in repository settings based off of the master branch.](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) After that is done, you can view all FTC Javadocs online without having to clone the repository.
![screenshot from 2016-09-17 13-23-39](https://cloud.githubusercontent.com/assets/13669330/18609853/0fcbed02-7cda-11e6-8c3c-ba14af9ba3e0.png)
Here's my fork, for example: https://nrizzio.github.io/ftc_app/doc/javadoc/index.html
After it is enabled, a link to https://ftctechnh.github.io/ftc_app/doc/javadoc/index.html could be added to the readme.

**Comment by richiksc** [comment]
Yes please! Host the Javadoc there and take the javadoc out of the repo, then add a download option for the javadoc on the wiki pages. Migrate the PDF tutorials to the wikis. I could do this for you guys if need be.

**Comment by cmacfarl** [comment]
Done.  See the readme.  Note that the javadoc was not taken out of the repo, but easy online access is now provided.
