### ISSUE TITLE
Robot config will not accept a "/" in the name

### ISSUE THREAD

**Issue by MikeModder** [ftctechnh/ftc_app#207]
Entering a "/" into the name field for a configuration causes the config to have a empty name in the list but the top right corner it shows up properly. Trying to activate to activate the null named config will cause the previous config to be loaded. This makes it show that no config is currently loaded. Also when inserting numbers in the text field with the "/" it sometimes crashes the app.

**Comment by rgatkinson** [comment]
Thank you for the bug report.

**Comment by rgatkinson** [comment]
This will be fixed in the next release.

**Comment by cmacfarl** [comment]
Fixed in beta.
