### ISSUE TITLE
Invalid Key Used: Vuforia App Key

### ISSUE THREAD

**Issue by alec500oo** [ftctechnh/ftc_app#208]
As the title says the license key seems to be causing an uncaught exception when a vision OpMode is run.

**Comment by rgatkinson** [comment]
Please have a look at the comments in the ConceptVuforiaNavigation opmode that provide instructions as to how you can obtain your own free, valid license key.

**Comment by alec500oo** [comment]
Thank you that changed from past versions I just noticed that comment.
