### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by aj-foster** [ftctechnh/ftc_app#218]
Hi folks,

I just wanted to drop a note to say thank you for your work on this project. It's obvious you put a lot of effort into making a platform that will allow students to succeed. Teaching with the SDK is great, and as an FTA, it's been a pleasure working with the latest updates.

Thanks for all of your hard work, and feel free to close this issue.

**Comment by 20esaua** [comment]
+1

**Comment by ajtrowell** [comment]
+1
