### ISSUE TITLE
Team Code Not Available Error

### ISSUE THREAD

**Issue by NutJobs** [ftctechnh/ftc_app#235]
We are getting an issue when putting code onto the phone.  A red box appears in the lower left corner saying" error running team code: default activity not found".  We have been working on trying to fix this, but no matter what we do it comes up.  Any ideas?

**Comment by cmacfarl** [comment]
Can you take a screenshot of Android Studio when you attempt to push the
app to the phone?  And then describe in detail the steps you take to do so?

**Comment by NutJobs** [comment]
Here is what we are doing when we get the error.

We plug in the phone with the Robot Controller installed on it and wait for it to connect. After it connects we press the green triangle run button or the debug run button beside it, and android studio instantly throws the  " error running team code: default activity not found" error box. 
![20161015_200057](https://cloud.githubusercontent.com/assets/22861994/19414188/b2a151e0-9312-11e6-96ad-97b9051439d9.jpg)

**Comment by magneticflux-** [comment]
@NutJobs You seems to have the ftc_app-master directory inside your project. Try deleting that.

**Comment by KingofGamesYami** [comment]
@magneticflux- that's normal for the `Project Files` tab.  Now, if they were on the `Android` tab I would be worried.

**Comment by cmacfarl** [comment]
Your build is failing.  The entire build log might shed some light.

In the image you can only see the last bit.  Although it sounds like your
SDK is corrupt.  Have you tried downloading a fresh zip file?

Craig

**Comment by magneticflux-** [comment]
@KingofGamesYami Ahh, I see. I'm typically in "Project" or "Android" so I was pretty confused about that extra folder.

**Comment by NutJobs** [comment]
We just downloaded a fresh zip.  This was a problem before and after.  Very frustrating.

**Comment by KevinEmery** [comment]
@NutJobs Is this problem persisting without you adding any of your code? By that, I mean follow the following steps.

 * Download a fresh zip file
 * Import that as a new project into Android Studio
 * Try to deploy the new project to your phones

If that fails, then it means this is a problem with either the project or your environment. If that succeeds (and then fails when you add your team's code to the project) then it is more likely an issue with your code.

**Comment by cmacfarl** [comment]
Can you please grab the entire build log, post it here and describe all of
the steps you are taking to download, open, and build your project?

**Comment by cmacfarl** [comment]
Please reopen if you are still seeing the problem.  Otherwise, closed.
