### ISSUE TITLE
Autonomous Timer

### ISSUE THREAD

**Issue by 2000andrewbowen** [ftctechnh/ftc_app#293]
Right now the 30 second autonomous timer does not reset after you stop autonomous. This can cause some problems when testing your autonomous if the timer is not reset manually. Is it possible to have the timer reset when the autonomous is stopped?

**Comment by MikeModder** [comment]
That would be awesome if this could be done.

**Comment by gearsincorg** [comment]
This has been added to the Developer issues list and the consensus is that it should be corrected.  
No ETA at this time.

**Comment by cmacfarl** [comment]
Fixed.
