### ISSUE TITLE
Android Studio reads this as bad code.

### ISSUE THREAD

**Issue by Based-Brian10** [ftctechnh/ftc_app#30]
![capture2](https://cloud.githubusercontent.com/assets/14338155/10179655/47448b66-66bc-11e5-90ba-696c171be1c0.PNG)
I have tried many code cleanup websites, but the issue the Studio is telling me is that I cannot resolve the symbol of OpModeRegister and I cannot resolve the method of .register. What is wrong and what must I do?

**Comment by WardBenjamin** [comment]
I have seen this error before. You most likely haven't installed the correct Android SDK versions. Post a picture of your SDK Manager? You need to install SDK 21 and a few tools.

**Comment by KevinEmery** [comment]
@WardBenjamin @Based-Brian10 You need to have the following SDK items installed according to the project configuration.

API 19 (SDK and Google APIs for ARM)
Build Tools v 21.1.2

This is contrary to the manual which instructs you to install API 21, but if you do this you will then need to install API 19 in order to run the project as it exists currently

**Comment by MeRPG** [comment]
Brian, you may have not run a gradle build yet. Dependencies such as the ftc sdk won't work until you build your project.

Thank you,
- Jaxon Brown

**Comment by ArchimedesPi** [comment]
Sync with Gradle (running a build will do this).

**Comment by buddytex** [comment]
@Based-Brian10 If you are still having this issue; It appears that you have an error in your build.gradle,  take a look at that and if you can not figure it out please post a screencap here so that we may help you out. I wish you luck!

**Comment by calebsander** [comment]
To second what others have been saying, we have seen this occur frequently before doing a Gradle Sync/Build. If you click "Build" (in the topmost menu) and then "Make Project", it should fix itself after a few seconds (wait until "Gradle Build Running" disappears from the bottom bar).

**Comment by hexafraction** [comment]
I've experienced the case where a misconfigured firewall/content filter combined with JVM certificate validation with HTTPS caused this issue as Gradle tried to fetch artifacts from JCenter. Could you post the Gradle log, as seen by "Show logs in explorer", as a [gist](https://gist.github.com), and providing a link to that gist here?

**Comment by Based-Brian10** [comment]
![robotic capture](https://cloud.githubusercontent.com/assets/14338155/10469137/fff818d4-71b7-11e5-8303-37df3a3ac634.PNG)
@buddytex @calebsander @MeRPG

**Comment by Based-Brian10** [comment]
![sdk managers](https://cloud.githubusercontent.com/assets/14338155/10469170/33738ae0-71b8-11e5-9225-7d8642a59278.PNG)
![tools](https://cloud.githubusercontent.com/assets/14338155/10469175/35c96db4-71b8-11e5-8bdb-1c7b332ef206.PNG)
@WardBenjamin 
@KevinEmery

**Comment by Based-Brian10** [comment]
@hexafraction I can't understand your question.

**Comment by calebsander** [comment]
You are putting Java code in your gradle script, so it obviously is going to fail. Reset FtcRobotController/build.gradle to how it was and then put your MecanumDefaultCode in its own .java file.

**Comment by Based-Brian10** [comment]
@calebsander how can I reset the code?

**Comment by calebsander** [comment]
Download the file from this repository and replace your current version with it.

**Comment by Based-Brian10** [comment]
@calebsander How do I put my Mecanum code in its own file?

**Comment by MeRPG** [comment]
@Based-Brian10 @calebsander
Or you could use the 'git reset' command in git bash. https://git-scm.com/docs/git-reset

@Based-Brian10 Here is how you should go about creating a new op mode:

![Creating a Class](http://i.imgur.com/2DM9LXQ.png)
![Creating a Class](http://i.imgur.com/Pfpbngk.png)
![Basic OPMode code](http://i.imgur.com/YIjsaFx.png)

Also be careful. The code visible in one of the screenshots you sent is NOT java. It actually looks like a wierd mixture between Java and WPILib from FRC last season.

More information on how to set Android Studio/IntelliJ IDEA up for FTC can be found here:
https://raw.githubusercontent.com/ftctechnh/ftc_app/master/doc/tutorial/FTCTraining_Manual.pdf
Especially from pages 87-108.

Hope I could help.

**Comment by ftctechnh** [comment]
Thanks to everyone who has assisted in this thread.  I am going to close this item out.  We would like to use this database to track verified issues/bugs with the systems.  Requests for assistance should be directed to the FTC Technology forum, or in this case to the Android Studio subforum:

http://ftcforum.usfirst.org/forumdisplay.php?159-Android-Studio

**Comment by TheOutlaws** [comment]
And I am having troubles my team wants me to program the robot to go straight then turn and thiks is my first year doing android could I get a push in the right direction for this program

**Comment by hexafraction** [comment]
@TheOutlaws This is not the correct venue for support. Please use the FTC official subforums for: [New FTC Technology](http://ftcforum.usfirst.org/forumdisplay.php?156-FTC-Technology) and [New FTC Technology > Android Studio](http://ftcforum.usfirst.org/forumdisplay.php?159-Android-Studio).
