### ISSUE TITLE
SDK Not Found

### ISSUE THREAD

**Issue by bhollers** [ftctechnh/ftc_app#342]
When updating to this newest version the gradle build fails with the following error:

Error:SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by magneticflux-** [comment]
@bhollers That appears to be an issue with the way your Android Studio installation is set up. There are solutions on StackOverflow such as this one: http://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil or this one: http://stackoverflow.com/questions/19794200/gradle-android-and-the-android-home-sdk-location

**Comment by cmacfarl** [comment]
Housekeeping
