### ISSUE TITLE
v3.1 has incorrect imports in samples, resulting in build errors

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#343]
`SensorAdafruitIMU.java` and `SensorAdafruitIMUCalibration.java` both reference old locations of `BNO055IMU` and/or `JustLoggingAccelerationIntegrator`. Looks like the code has been copied into the sample programs `SensorBNO055IMU` and `SensorBNO055IMUCalibration` but the old programs were never deleted. Teams should be supplied versions of the SDK that build without errors.

**Comment by ftctechnh** [comment]
Thanks Caleb!

**Comment by ftctechnh** [comment]
Issue should be fixed.  Thanks again Caleb!
