### ISSUE TITLE
Rev Color/Distance Sensor is missing

### ISSUE THREAD

**Issue by LuisWiki** [ftctechnh/ftc_app#346]
Hi ,
 I cant find in external/samples the file for the REV Color/Distance Sensor, the Readme says it had been implemented in the Alpha version... I already change the branch to alpha and beta but it isn´t anywhere. 

Is the file in other place? O how can I start using this sensor in java? 

Thank You.

**Comment by RedfishRobotics** [comment]
Apologies if this isn't the correct way to reply.

We implemented the REV Color sensor using the same code samples that are
available for the AdaFruit sensor and it worked perfectly with few changes.

We did have to change the "CDIM" portion of the sample code as the REV
system doesn't have a CDIM (Just commented it out)

And you might have to change the port entry if you need to turn the LED
on/off.

We can send the code if you're still stuck.



Michael P Clark
Founder/Lead Mentor


Redfish Robotics, LLC
"We're Hooked on *FIRST*­®"

2017 FRC Bayou Regional Volunteer of the Year

http://www.redfishrobotics.com
Phone: 985-80F-TC10
Twitter: @FIRSTMentorMike <https://twitter.com/firstmentormike>

**Comment by LuisWiki** [comment]
Thank you for the reply , it works fine with the Adafruit sample.
