### ISSUE TITLE
Sdk is too low

### ISSUE THREAD

**Issue by gunrh1231** [ftctechnh/ftc_app#353]
Error:The SDK Build Tools revision (23.0.3) is too low for project ':FtcRobotController'. Minimum required is 25.0.0
<a href="openFile:E:/AndroidStudioProjects/ftc_app-master/FtcRobotController/build.gradle">Open File</a>

how to fix

**Comment by magneticflux-** [comment]
Replace "23.0.3" with "25.0.2" in some `.gradle` file.

**Comment by gunrh1231** [comment]
Error:(23, 0) Could not get unknown property 'Focus' for repository container.
<a href="openFile:E:\AndroidStudioProjects\ftc_app-master\FtcRobotController\build.gradle">Open File</a>

**Comment by gunrh1231** [comment]
now i got this error

**Comment by magneticflux-** [comment]
@gunrh1231 Can you paste the `.gradle` file that is causing the error here using a code block? Just surround it with "\`\`\`".
Example:
\`\`\`
Code here...
\`\`\`
Becomes
```
Code here...
```

**Comment by gunrh1231** [comment]
> I FIX IT THANK YOU

**Comment by magneticflux-** [comment]
@gunrh1231 If you're sure it's fixed, you can mark the issue as solved using the "Close" button.

**Comment by brandon0x52** [comment]
Just for clarification / help of anyone else who encounters this issue, can you explain how you were able to fix it, @gunrh1231?
