### ISSUE TITLE
Gradle Build Error

### ISSUE THREAD

**Issue by AryakTheBoss** [ftctechnh/ftc_app#354]
Error:(15, 0) Could not find method android() for arguments [build_8amacim86tzuitjwh24lf3iz7$_run_closure1@78e509b8] on root project 'ftc_app-master' of type org.gradle.api.Project.

This is what happens when i import the project into Android Studio Fresh from github
first error was Could not find build tools revision (fixed by opening project structure and adding it)

Thanks in advance

**Comment by magneticflux-** [comment]
@AryakTheBoss Can you paste the `.gradle` file that is causing the error here using a code block? Just surround it with "\`\`\`".
Example:
"\`\`\`"
Code here...
"\`\`\`"
Becomes
```
Code here...
```
