### ISSUE TITLE
null references in java :shocked:

### ISSUE THREAD

**Issue by fwprobotics** [ftctechnh/ftc_app#373]
error is thrown on app startup, robot status is `EMERGENCY STOP`
restarting robot does not work

```
Error: unable to create robot: Robot failed to start: Attmept to invoke interface method 'boolean com.qualcomm.robotcode.hardware.configuration.ConfigurationType.isDeviceFlavor(com.qualcomm.robotcode.hardware.configuration.UserConfigurationType$Flavor)' on a null object reference
```

**Comment by qwertychouskie** [comment]
This sounds like an issue with your code, not the SDK itself.  Try posting on the forum.

**Comment by knxtdoor** [comment]
We had this issue, disabling instant run in Android Studio fixed it for us.

**Comment by devsnek** [comment]
@qwertychouskie i don't call those methods anywhere in my code or i would have checked that first

@knxtdoor thanks i'll try that when i'm in the shop next (on tuesday)

**Comment by brandon0x52** [comment]
I agree with @knxtdoor, if you take a look at #350 that is the same null reference I was getting. Turning off Instant Run in Android Studio was the fix for me as well. Let us know how it goes!

**Comment by devsnek** [comment]
awesome i'll close this (or not 👀 ) after i test

**Comment by cmacfarl** [comment]
Instant run is very problematic.  The official line is that all teams using AS should turn it off.  Unfortunately with Google making the decision to enable it by default, this is hard to accomplish.

**Comment by fwprobotics** [comment]
it worked, thanks
