### ISSUE TITLE
wifi direct does not

### ISSUE THREAD

**Issue by hadronknights** [ftctechnh/ftc_app#374]
With the latest ftc-app code 3.4 and with 3.5 rc app and 3.5 ds app, configuring wifi setting does not work. DS tries few times and gives up.

**Comment by devsnek** [comment]
i had the same issue today and fixed it by disabling all wifi direct settings, clearing all saved connections for wifi direct, then doing the config only through the app, not android settings

**Comment by hadronknights** [comment]
How do you setup using the app? Thank you

**Comment by hadronknights** [comment]
We can connect now. Thank you @devsnek. But now we can't configuration. Edit option only allows us to scan but scanning is not working  even if   robot/rev expansion hub is connect and RC app is running. Any ideas?

**Comment by WardBenjamin** [comment]
@hadronknights if the specific WiFi Direct problem is solved, please close this issue.

**Comment by 20avva** [comment]
@hadronknights check out #484. Sorry if I’m late

**Comment by opdollar** [comment]
hello , found a solution to this, check that do not disturb.

**Comment by opdollar** [comment]
never mind my team miss informed me.
