### ISSUE TITLE
RelicRecoveryVuMark and VuMarkInstanceId missing from FTC SDK

### ISSUE THREAD

**Issue by dominicap** [ftctechnh/ftc_app#381]
Both RelicRecoveryVuMark and VuMarkInstanceId seem to be missing from the latest FTC SDK (v3.4). Thus 'ConceptVuMarkIdentification' does not compile.
<img width="1217" alt="screen shot 2017-09-11 at 11 41 30 am" src="https://user-images.githubusercontent.com/13564850/30283793-18823776-96e7-11e7-82de-076a4bb88bfe.png">

Any assistance would be appreciated.

**Comment by gearsincorg** [comment]
I concur.  I have built these samples from an unmodified (except for the
//@Disable line) FTC_APP zip download.

Note: If you have just downloaded, remember that you should "re-import" the
project.

Phil.




Phil Malone
GEARS Inc.

phil.malone@mr-phil.com
Office: 301.387.2331
Mobile: 301.501.7424

**Comment by cmacfarl** [comment]
> Note: If you have just downloaded, remember that you should "re-import" the project.

Alternatively "Clean Project" followed by "Rebuild Project"

**Comment by dominicap** [comment]
My bad, after re-cloning, the issue no longer persists. Thanks!
