### ISSUE TITLE
DbgLog.class missing from latest release

### ISSUE THREAD

**Issue by Timberline10435** [ftctechnh/ftc_app#397]
With newest code, DbgLog isn't resolved.  Looking at classes.jar from the zip file, I see it is no longer there.

**Comment by cmacfarl** [comment]
DbgLog was removed as it duplicated RobotLog functionality and it was deemed that we didn't need both.  RobotLog.d() is likely what you want.

**Comment by Timberline10435** [comment]
Thanks for the info.  Can you add that to the Readme for 3.4?  Where might we find documentation of RobotLog?  We see it's in com.qualcomm.robotcore.util.RobotLog.

**Comment by ftctechnh** [comment]
@Timberline10435 
Great suggestion.  Will do (update readme to reflect DbgLog removal).

**Comment by markshancock** [comment]
This change caused our team some initial startup challenges.
It would have helped us if you had deprecated the class rather than deleting it.
http://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/deprecation/deprecation.html
