### ISSUE TITLE
Color Sensor

### ISSUE THREAD

**Issue by FTC0265** [ftctechnh/ftc_app#42]
We are unable to import the Color Sensor files even though they are in the directory. Can you fix this?

**Comment by ftctechnh** [comment]
Hi FTC0265,

I am sorry that you are experiencing an issue.  I'm not sure if I understand your question.  Could you clarify what you are attempting to do?  Are you trying to write an op mode that uses the color sensor but are having problems?  Or have you written an op mode that uses a color sensor but you do not see them listed in the Op Mode selection on the Driver Station?

Also, I think you would get a better response and more people helping you if you were to post your question on the FTC Technology forum:

http://ftcforum.usfirst.org/forumdisplay.php?156-FTC-Technology

Would you mind reposting your question (with some additional detail) over on the FTC Technology forum?

Sincerely,

Tom

**Comment by FTC0265** [comment]
We are trying to use a Modern Robotics Color Sensor with the newly updated github files. Whe we try to import the color sensor files using the import com.qualcomm.robotcore.hardware.ColorSensor; the ColorSensor part turns red and it says that it cannot recognize this symbol. Is the program just not finding the ColorSensor files in the directories?

**Comment by Ace314159** [comment]
Go to `File`->`Invalidate Caches...` Then click on `Invalidate Caches and Restart`.

**Comment by TheOutlaws** [comment]
And I am having troubles my team wants me to program the robot to go straight then turn and thiks is my first year doing android could I get a push in the right direction for this program

**Comment by agent22922** [comment]
The colorsensor class is not available in the library, but there is examples of using it, javadoc etc.. Can someone point to a valid like for sdk download that has colorsensor class in it ?

**Comment by Ace314159** [comment]
When you create an object using the colorsensor class, does the code build
properly?

**Comment by agent22922** [comment]
Not able to build because it says that there are errors on the program

**Comment by agent22922** [comment]
Never Mind when we did what @Ace314159 we didnt get an error
