### ISSUE TITLE
DcMotorSimple Javadoc Mistake

### ISSUE THREAD

**Issue by jeffless** [ftctechnh/ftc_app#457]
In the Javadoc for the DcMotorSimple interface, it states that the setPower and getPower methods should have "a value in the interval [0.0, 1.0]." However this is inaccurate, as the setPower command has a range of [-1.0, 1.0]. This can be potentially confusing for teams getting started.

**Comment by cmacfarl** [comment]
That's a good observation.   Thanks for the correction.

**Comment by cmacfarl** [comment]
Fixed in next release.
