### ISSUE TITLE
Configuration files are stored separately from the selected file

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#47]
The XML configuration files are stored in /sdcard/FIRST but the name of the selected one is not. This means that the configuration files persist when you update the app or build it from a new computer, but the selected file is not. For teams who plan to use multiple computers to build the app, it would be nice to save the name of the selected file so that they don't have to constantly re-activate it.

**Comment by qwertychouskie** [comment]
I have never noticed this issue, probably been fixed.

**Comment by calebsander** [comment]
Yeah, the issue still exists but the fact that the key used to sign the app is now included in the repository means that this poses less of a problem.
