### ISSUE TITLE
Difference between pushbotteleopPOV_linear and pushbotteleopTank_iterative??

### ISSUE THREAD

**Issue by adryavitia** [ftctechnh/ftc_app#480]

**Comment by gearsincorg** [comment]
yes

**Comment by cmacfarl** [comment]
If there's a question here, it's better asked over on r/FTC or the FTC forums.   You'll get more traction and help on those communities.

https://www.reddit.com/r/FTC/
https://ftcforum.usfirst.org/forum

The issue list should be reserved for genuine "issues".
