### ISSUE TITLE
Modern Robotics Color sensor throwing weird exceptions

### ISSUE THREAD

**Issue by Sass-Meister** [ftctechnh/ftc_app#49]
I'm trying to run the code colorsensordriver.java and after fixing some of the obvious issus like haveing the wrong maping and stuff I ran into an exception that didnt really give me much insite into the problem. "User code threw an uncaught exception: null" is the error it threw. If any more information is needed just ask. If anyone has had this happen to them and knows how to fix it, please let me know.

**Comment by JacobAMason** [comment]
This could be an issue within some of your own code. Create a Gist (look at the top of this page) and paste in the opMode. (Alternatively, if you've already committed this code to your fork of the ftc_app repo, you can link us to the opMode in question.)

**Comment by Sass-Meister** [comment]
This is the code i'm running to get a better understanding on the color sensor and the system this year

https://github.com/Crorem/ftc_app_5452/blob/master/FtcRobotController/src/main/java/com/qualcomm/ftcrobotcontroller/opmodes/demos/ColorSensorDriver.java

I'm still learning java so if this is some stupid mistake, let me know.

**Comment by Sass-Meister** [comment]
Oh wait, I saw what I did wrong, commented it out and now it works.

**Comment by TheOutlaws** [comment]
And I am having troubles my team wants me to program the robot to go straight then turn and thiks is my first year doing android could I get a push in the right direction for this program
