### ISSUE TITLE
Version 3.6 of the RC has not yet been pushed to the Play Store

### ISSUE THREAD

**Issue by NoahAndrews** [ftctechnh/ftc_app#496]
Only the DS has been updated.

**Comment by gebailey** [comment]
According to:
https://play.google.com/store/apps/details?id=com.qualcomm.ftcdriverstation

It appears that the driver station APK is also 3.5 on the play store.

**Comment by NoahAndrews** [comment]
The DS listing shows 3.6 for me, and we updated our DS to 3.6 from the play store.

**Comment by gearsincorg** [comment]
You have to be careful, and not read the number of stars (3.5) as the
revision.

I can confirm that the RC is really only 3.5.
It's odd that you can't include the version in the play store info.
somewhere.

Phil.

Phil Malone
GEARS Inc.

phil.malone@mr-phil.com
Office: 301.387.2331
Mobile: 301.501.7424
