### ISSUE TITLE
None of our sensor working

### ISSUE THREAD

**Issue by maylee0515** [ftctechnh/ftc_app#501]
We haven't been able to get any of our sensors to work....We have no idea why cause our sensors worked when we made separate codes for each one of them. Even when I tried the exact same code, it still does not work.

**Comment by NoahAndrews** [comment]
How do they not work? Do they return bad values? Is there an error?

**Comment by maylee0515** [comment]
There was a problem but we found a new core device module and were able to fix the problem. Thanks anyway.

**Comment by NoahAndrews** [comment]
Great! Go ahead and press the close issue button.
