### ISSUE TITLE
Error running TeamCode: Default Activity not found 

### ISSUE THREAD

**Issue by J053Fabi0** [ftctechnh/ftc_app#506]
I have this issue since the new update of Android Studio. Even with the ftc_app original project, without modifying it. My friend is having the same problem, so its not only me.

[![Captura_de_pantalla_2018-01-12_a_la_s_14.55.14.png](https://s13.postimg.org/5h8nfce6f/Captura_de_pantalla_2018-01-12_a_la_s_14.55.14.png)](https://postimg.org/image/4rpv2zdmr/)

[![Captura_de_pantalla_2018-01-12_a_la_s_14.56.07.png](https://s13.postimg.org/7lt0go85z/Captura_de_pantalla_2018-01-12_a_la_s_14.56.07.png)](https://postimg.org/image/9dlzbkrir/)

### Any idea on how to solve it?

**Comment by cmacfarl** [comment]
What happens if you select File -> Invalidate Caches / Restart... ?

**Comment by J053Fabi0** [comment]
I have tried that before... without luck

**Comment by cmacfarl** [comment]
What are the contents of your AndroidManifest.xml file?   Located under FtcRobotController -> manifests?

**Comment by J053Fabi0** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="com.qualcomm.ftcrobotcontroller"
          android:versionCode="21"
          android:versionName="3.1">

  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

  <application
    android:allowBackup="true"
    android:largeHeap="true"
    android:icon="@drawable/ic_launcher"
    android:theme="@style/AppTheme" >

    

    

    
    <service
      android:name="com.qualcomm.ftccommon.FtcRobotControllerService"
      android:enabled="true" />

    

  </application>

</manifest>`

**Comment by J053Fabi0** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="com.qualcomm.ftcrobotcontroller"
          android:versionCode="21"
          android:versionName="3.1">

  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

  <application
    android:allowBackup="true"
    android:largeHeap="true"
    android:icon="@drawable/ic_launcher"
    android:theme="@style/AppTheme" >

    

    

    
    <service
      android:name="com.qualcomm.ftccommon.FtcRobotControllerService"
      android:enabled="true" />

    

  </application>

</manifest>

**Comment by J053Fabi0** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="com.qualcomm.ftcrobotcontroller"
          android:versionCode="21"
          android:versionName="3.1">

  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

  <application
    android:allowBackup="true"
    android:largeHeap="true"
    android:icon="@drawable/ic_launcher"
    android:theme="@style/AppTheme" >

    

    

    
    <service
      android:name="com.qualcomm.ftccommon.FtcRobotControllerService"
      android:enabled="true" />

    

  </application>

</manifest>

**Comment by J053Fabi0** [comment]
http://josefabio.me/AndroidManifest.xml

**Comment by J053Fabi0** [comment]
[![Captura_de_pantalla_2018-01-12_a_la_s_17.29.43.png](https://s13.postimg.org/o9p3x07rr/Captura_de_pantalla_2018-01-12_a_la_s_17.29.43.png)](https://postimg.org/image/k0kduu4ib/)

**Comment by magneticflux-** [comment]
@J053Fabi0 It should be [this](https://github.com/ftctechnh/ftc_app/blob/6370c4e556d6f6f1069659372323cfbbbc7f2dcb/FtcRobotController/src/main/AndroidManifest.xml).

**Comment by J053Fabi0** [comment]
[![Captura_de_pantalla_2018-01-12_a_la_s_17.36.28.png](https://s13.postimg.org/42bo4vac7/Captura_de_pantalla_2018-01-12_a_la_s_17.36.28.png)](https://postimg.org/image/iya7cglqr/)

**Comment by magneticflux-** [comment]
@J053Fabi0 Those references are red either because the project has never been successfully built or because the files they reference are missing. Those files should be (and are) included in the current latest version and prior versions.

**Comment by cmacfarl** [comment]
You are definitely missing the activity declaration in the first manifest file you posted.  

What is your process for obtaining the FTC SDK?  If you switch to a new empty directory, do a git clone https://github.com/ftctechnh/ftc_app.git, (assuming of course you have a git client on your machine) open that project and build, do you get the same error?

**Comment by J053Fabi0** [comment]
@cmacfarl The error doesn't show if the project is the original O_o
But I have this warnings:
[![Captura_de_pantalla_2018-01-12_a_la_s_21.09.34.png](https://s17.postimg.org/b681dvden/Captura_de_pantalla_2018-01-12_a_la_s_21.09.34.png)](https://postimg.org/image/4305y97yz/)

**Comment by J053Fabi0** [comment]
Nvm, I solve them. Thanks for the help guys! Ur the best
