### ISSUE TITLE
Try to try autonomous but it won't intilaize

### ISSUE THREAD

**Issue by saivee** [ftctechnh/ftc_app#514]
I try to test autonomous but then it won't init. After I restart it says everything is missing. Can anybody help? We have a comp on Feb.3  so we need a quick response.

**Comment by cmacfarl** [comment]
You'll get better traction on this question if you ask over on reddit at r/FTC.

To get the best help try to be as complete as possible.  Post your software somewhere, take screenshots of your phone, describe your hardware setup etc.  This will help the community narrow down your problem as quickly as possible.
