### ISSUE TITLE
CDIM - unable to save configuration to file with more than one sensor configured.

### ISSUE THREAD

**Issue by AlecHub** [ftctechnh/ftc_app#53]
When configuring the CDIM with more than one sensor (say COLOR_SENSOR and TOUCH_SENSOR), I am unable to save the configuration due to the following error:

![save-error](https://cloud.githubusercontent.com/assets/15099062/10795678/48750260-7d71-11e5-9a0e-90f08c8fc2d4.png)

The logcat merely echos the same error and provides no additional information as to the cause of the error.  The configuration saves successfully when only one sensor is configured.

**Comment by AlecHub** [comment]
I should have known that the sensors need to be named.  Naming the sensors resolves the issue.

Perhaps this ticket can be a feature request for the UI to prevent configuring a sensor with no name.

**Comment by gearsincorg** [comment]
Or... it would be helpful to provide some more information as to which type of device has the blank names...

**Comment by AlecHub** [comment]
I believe I mentioned it was a COLOR_SENSOR and TOUCH_SENSOR.  

BTW, how did you get to be a "collaborator", and why can't non-collaborators assign labels to their own tickets?

**Comment by gearsincorg** [comment]
AlexHub.  You miss-read my response.  I was suggesting that the Error message should provide more information regarding which devices had blank names, not you ;)

Error messages that don't give you enough information to correct the problem are not very useful.
Sorry for the confusion.

Phil.

**Comment by AlecHub** [comment]
Hi Phil... Yes, I misread your comment, and yes more info to correct the problem is needed.  Thanks, Alec.

**Comment by gearsincorg** [comment]
Closed, as this issue relates to previous season code.
