### ISSUE TITLE
OpModeRegister

### ISSUE THREAD

**Issue by archishou** [ftctechnh/ftc_app#534]
I'm having an issue where when I delete an opmode, the opmode still shows up on the phone. With the error of a duplicate opmode. I'm using annotations to register an opmode. Is there any fix for this? Thank you.

**Comment by NoahAndrews** [comment]
Are you using OnBotJava?

**Comment by qwertychouskie** [comment]
Probably a duplicate of https://github.com/ftctechnh/ftc_app/issues/517, try `Build->Clean Project`.

**Comment by archishou** [comment]
Yup thank you!
