### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. It will be removed at the end of 2018.

### ISSUE THREAD

**Issue by whyiamafool** [ftctechnh/ftc_app#546]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

This warning is shown as a Gradle Sync Issues for TeamCode/build.gradle and FtcRobotController/build.gradle

How do I fix this?

**Comment by NoahAndrews** [comment]
Ignore it, it will be gone in the software for next season.

**Comment by whyiamafool** [comment]
@NoahAndrews, when will the ftc_app for next season release?

**Comment by NoahAndrews** [comment]
I'm afraid I don't speak for FIRST.

**Comment by dadosch** [comment]
In FtcRobotController's and TeamCode's gradle file (build.gradle @ TeamCode and build.release.gradle @ FtcRobotController) change "compile" to "implementation". It should work, but no warranties :smile:

**Comment by JBYoshi** [comment]
This should probably be fixed by FIRST as well.

**Comment by NoahAndrews** [comment]
Thanks for bringing this back up. Turns out we only fixed it for the internal build.

**Comment by rwoodley** [comment]
Can you tell us what the fix is so we can implement it now? Or point us to a commit?

**Comment by dmssargent** [comment]
Take a look at the current alpha: https://github.com/ftctechnh/ftc_app/commit/58d723a1d11a1c03ffb3a30f4a38c3601eac61d8#diff-a1a86c17a464097b827eab71781245d2R2
