### ISSUE TITLE
Driver Station Joystick Assignment Duplicity

### ISSUE THREAD

**Issue by ftc2843** [ftctechnh/ftc_app#55]
Press Start-A on a gamepad.  The icon above User 1 appears.
Press Start-B on the same gamepad.  The icon above User 2 appears.  However, the icon above User 1 doesn't disappear.  At this point only one gamepad is active, but two icons are shown.
Press Start-B on the other gamepad.  Both icons are shown, but the first gamepad no longer operates the robot.
The team/FTA/CSA/etc. may become confused seeing both icons when only one gamepad is active.

**Comment by calebsander** [comment]
Can confirm.

**Comment by calebsander** [comment]
Confirmed to still be an issue in the 16.01.04 release.

**Comment by calebsander** [comment]
Fixed in today's release.

**Comment by ftctechnh** [comment]
This was fixed with version 16.02.09
