### ISSUE TITLE
DS automatically turns Wi-Fi on

### ISSUE THREAD

**Issue by FROGbots-4634** [ftctechnh/ftc_app#564]
Again, I'm not sure if this is intentional or not, but: when cold-launching the SDK v4.0 DS app, if Wi-Fi is off, it is turned on automatically. I feel like it isn't really intentional though, because the RC doesn't do it, only the DS.

**Comment by cmacfarl** [comment]
Very perceptive.  Yes this is intentional.  And yes. You are right the RC at present does not do this.
