### ISSUE TITLE
OnBot to Blocks?

### ISSUE THREAD

**Issue by chexbox** [ftctechnh/ftc_app#586]
It seems easy to export Blocks to OnBot, but not back. How do I convert OnBot Java to Blocks?

**Comment by NoahAndrews** [comment]
Java is a much less restrictive programming environment than Blocks is, so it wouldn't be feasible to support converting arbitrary Java code into Blocks.

**Comment by NoahAndrews** [comment]
The purpose of the conversion feature is to help teams migrate to and learn a more advanced programming environment. Converting from Blocks to Java serves that goal much better than the reverse.
