### ISSUE TITLE
Error code on Android Studio

### ISSUE THREAD

**Issue by SoaringWillow** [ftctechnh/ftc_app#587]
The error code is showing below.
<img width="1409" alt="2018-10-05 12 54 35" src="https://user-images.githubusercontent.com/43420010/46548834-2d961a80-c89e-11e8-8381-79aa2a0a114e.png">

**Comment by cmacfarl** [comment]
You've updated to AS 3.2 and google broke the build by not packaging appt2 with 3.2.

Until the Tech Team provides a release that supports 3.2 natively, the solution is to patch this

  https://github.com/ftctechnh/ftc_app/pull/581/files#diff-c197962302397baf3a4cc36463dce5ea

into your build.gradle file.

**Comment by TigranTT** [comment]
change in "build.gradle" and add highlighted. 
![screen shot 2018-10-05 at 11 05 29 pm](https://user-images.githubusercontent.com/25997101/46567147-4c72cc00-c8f3-11e8-814a-62dac41f1f45.png)

 'compile' is obsolete and has been replaced with 'implementation' and 'api'. 
change it in "build.release.gradle"
![screen shot 2018-10-05 at 11 06 09 pm](https://user-images.githubusercontent.com/25997101/46567149-54327080-c8f3-11e8-8a84-4c51545ee49e.png)

**Comment by cmacfarl** [comment]
The implementation change is in the alpha on ftctechnh/ftc_app.  It's
not strictly needed to fix the build break referenced.   The
repositories block addition is needed to fix the build break related
to google's moving around of dependencies in the 3.2 build tools.

**Comment by cmacfarl** [comment]
Fixed with 4.3 by adding the external repositories to the dependencies block.
