### ISSUE TITLE
Using external camera requires new vuforia key

### ISSUE THREAD

**Issue by qwertychouskie** [ftctechnh/ftc_app#633]
ConceptTensorFlowObjectDetection works but ConceptTensorFlowObjectDetectionWebcam causes an emergency stop. It gives `VuforiaException - Vuforia failed to start: phase=PreInit`.  Generating a new Vuforia key fixes this, but the error message is very unclear.

**Comment by FROGbots-4634** [comment]
Seconded on both counts.

**Comment by geekpersonman** [comment]
thirded

**Comment by FROGbots-4634** [comment]
@cmacfarl why was this closed?

**Comment by cmacfarl** [comment]
It's been fixed internally and will be in next season's release.
