### ISSUE TITLE
Vuforia shows black 

### ISSUE THREAD

**Issue by dwc54** [ftctechnh/ftc_app#649]
i am using vuforia with a usb webcam with open cv puling frames from vuforia after running that program 
3-10 times when vuforia is started it just shows black and i cannot get the frame. 
Rebooting the phone fixes it, unplugging the cpdm makes the image work but when it is pluged back in the phone reboots.
I am using samsung galaxy s5 with sdk 4.3

**Comment by NoahAndrews** [comment]
Make sure you're using a powered USB hub

**Comment by dwc54** [comment]
i am not

**Comment by NoahAndrews** [comment]
Right, try using one.

**Comment by cmacfarl** [comment]
Something along the lines of this.

https://www.amazon.com/gp/product/B0192LPK5M/ref=oh_aui_detailpage_o08_s00?ie=UTF8&psc=1

It can be used with a USB battery pack.

**Comment by dwc54** [comment]
i will try that
