### ISSUE TITLE
How can I call an opmode to run inside of another opmode?

### ISSUE THREAD

**Issue by pa12031876** [ftctechnh/ftc_app#668]
When programming an autonomous program, the code can get very long. I wanted to confirm if there is any way to call another opmode to start while the original is still running? Thank You!

**Comment by cmacfarl** [comment]
No.  Running of opmodes is managed by the underlying SDK.  

But I don't think this is necessarily a question about running of opmodes.  It's rather a question of software design and architecture.  This is better asked and answered on the forums or r/FTC over on reddit.
