### ISSUE TITLE
Robot Controller App Crashing when Connecting to Driver Station

### ISSUE THREAD

**Issue by danielgrimshaw** [ftctechnh/ftc_app#69]
This was the only interesting feature in the log, it was just before it crashed:
Fatal signal 13 (SIGPIPE) at 0x00001522 (code=0), thread 5410 (sh)
11-06 16:21:29.816 I/Timeline( 5458): Timeline: Activity_idle id: android.os.BinderProxy@41951900 time:991409

**Comment by gearsincorg** [comment]
Closed, as this issue relates to previous season code.
