### ISSUE TITLE
Driver Station code repo?

### ISSUE THREAD

**Issue by HewwoCraziness** [ftctechnh/ftc_app#694]
Hi, I'm looking to add functionality to my team's fork of the Robot Controller (not currently for competition use), but I need to add code to the Driver Station as well. Is there a repository for that code somewhere? (All I've found is the APK in the releases.)

**Comment by NoahAndrews** [comment]
The Driver Station source is not available publicly.

**Comment by FROGbots-4634** [comment]
@HewwoCraziness FYI, the develop branch of OpenRC now contains reverse engineered source code for Driver Station v3.7
