### ISSUE TITLE
[Q] How has the RoverRuckus.tflite file for Tensorflow been generated?

### ISSUE THREAD

**Issue by dadosch** [ftctechnh/ftc_app#697]
as it appears not to be regular text…

**Comment by cmacfarl** [comment]
A google intern trained the machine over the summer.  More information on TEnsorFlow here: https://www.tensorflow.org/

**Comment by NoahAndrews** [comment]
See this repository for more information https://github.com/google/ftc-object-detection

**Comment by NoahAndrews** [comment]
And this folder in particular https://github.com/google/ftc-object-detection/tree/master/training
