### ISSUE TITLE
Joystick support in driver station

### ISSUE THREAD

**Issue by pbrier** [ftctechnh/ftc_app#7]
I cannot seem to get the Logitech F310 joystick working on many (european) Android phones.
With the switch in "X" position it is seen as a USB device with VID=0x046d and PID=0xC21D, but the DriverStation app does not detect the joystick.

(I can see the USB data from the controller when I use the tincore App on the same phone).

See for more information:
https://github.com/pbrier/ftc_app/wiki/Logitech-F310-controller
https://github.com/pbrier/ftc_app/wiki/Tested-Devices

**Comment by leoforney** [comment]
Try testing hitting the mode button and see if it turns green.

We had a similar issue and If you are using a ZTE Speed, our first phone had very bad issues detecting the controller, so we used one of our other phones and it worked. Also press the Start button + X.

**Comment by ftctechnh** [comment]
Hi pbrier,

I am going to close this question out.  We would like to use this database to track known issues/bugs with the system.  

If you need assistance troubleshooting your robot, please visit the FTC Technology forum.  This issue tracking DB should be reserved for verified bugs/issues.

http://ftcforum.usfirst.org/forumdisplay.php?156-FTC-Technology

Thanks!

Tom

**Comment by TheOutlaws** [comment]
And I am having troubles my team wants me to program the robot to go straight then turn and thiks is my first year doing android could I get a push in the right direction for this program
