### ISSUE TITLE
Driver Station app will not open drop down OpMode selector

### ISSUE THREAD

**Issue by danielgrimshaw** [ftctechnh/ftc_app#70]
When connected, the Driver Station app is unable to load the OpMode drop down list.

**Comment by Sass-Meister** [comment]
Does it provide an error of any sort? Also are you putting your program onto the robot controller by hitting run on android studio?

**Comment by magneticflux-** [comment]
@danielgrimshaw Please provide reliable steps to reproduce the problem.

**Comment by danielgrimshaw** [comment]
Problem has been found and corrected. Problem is in issue https://github.com/ftctechnh/ftc_app/issues/79.
