### ISSUE TITLE
v5.0 SDK Available

### ISSUE THREAD

**Issue by AlecHub** [ftctechnh/ftc_app#718]
This issue is intended to notify folks that watch this repository that the v5.0 SDK is available in a new repository that was created for the SkyStone season: https://github.com/FIRST-Tech-Challenge/SkyStone

The NOTICE posted in the SkyStone repository explains the need for a new repository for the SkyStone season.

Be sure to click on the Watch button in the SkyStone repository.

**Comment by cmacfarl** [comment]
v5.0 is also in the beta branch here ([ftechnh/ftc_app](https://github.com/ftctechnh/ftc_app/tree/beta)).

**Comment by rbrott** [comment]
Is the alpha branch still in use?

**Comment by cmacfarl** [comment]
Nope.

**Comment by cmacfarl** [comment]
v5.0 beta has been promoted to master.
