### ISSUE TITLE
Error in code is pointing to non existent source files

### ISSUE THREAD

**Issue by Zach-coder** [ftctechnh/ftc_app#743]
I'm trying to write a base code for our robot and getting errors that are not related to the code I'm writing but that are pointing to entire files within the FTC library that I cannot find. My team got new phones this year and we are now using the Moto E5 Play if that makes any difference.

**Comment by cmacfarl** [comment]
Do you have build logsm and can you post your software somewhere public (github would be ideal)?

**Comment by Zach-coder** [comment]
I have a repository set up on github.
Repository name is 9507-RD-Code

**Comment by cmacfarl** [comment]
Github search has no results for 9507-RD-Code.  Can you post the full url to the repository?

Also build logs would be helpful.

Note that sometimes Android Studio goes off in the weeds and gives build errors that are not related to FTC software.  When that happens I typically do File -> Invalidate Caches and Restart to fix the problem.

**Comment by Zach-coder** [comment]
Thank you. At this point I fixed the problem. I removed the old FTC source code and reinstalled this years version. I think I missed one of the old source code files. I wiped android studio and re-downloaded the new source files.
