### ISSUE TITLE
PID control in the android system

### ISSUE THREAD

**Issue by Sass-Meister** [ftctechnh/ftc_app#75]
When we were using robotc last year, all we had to do to activate PID control. Is there a system like this for the new system? I skimmed through the documentation and there doesn't see to be any support for it except things like motor.setEncoderTarget();.PID control was super useful and new teams may not even realize they need to put a system in place to smooth out the motor.

**Comment by KyleDavidE** [comment]
`motor.setMode(DcMotorController.RunMode.RUN_USING_ENCODERS);` should do the trick.


Note that in past versions it has been `setChannelMode` but that naming has been deprecated.

- 8391 W-Prime robotics.

**Comment by Sass-Meister** [comment]
Ok thanks

**Comment by calebsander** [comment]
Can this be closed?
