### ISSUE TITLE
Driver for Grove AS5600 magnetic rotary position sensor

### ISSUE THREAD

**Issue by vwestin** [ftctechnh/ftc_app#755]
I wrote a driver for the Grove AS5600 magnetic rotary position sensor. Any chance I can share the code for inclusion into a future release?

**Comment by shadowhen89** [comment]
This repository is not being maintained by FIRST anymore. If you want to open an issue, I would suggest opening one in a [current maintained repository](https://github.com/FIRST-Tech-Challenge/SkyStone).

**Comment by vwestin** [comment]
OK, thanks.
