### ISSUE TITLE
Sensor (etc) APIs should be interfaces, not abstract classes

### ISSUE THREAD

**Issue by rgatkinson** [ftctechnh/ftc_app#95]
Abstract classes artificially constrain implementation approaches. Pure interfaces capture the essentials of the API contract without impacting choices of implementation. ColorSensor, CompassSensor, etc should be interfaces, not abstract classes.

**Comment by calebsander** [comment]
Is there a reason why this was closed? This seems like a desirable change, as only `toString()` is implemented in each of the classes. It seems like it would make more sense to have, for example, all the HiTechnic sensor classes extend a common class that would make dealing with the legacy module easier.

**Comment by calebsander** [comment]
Fixed in today's release.
