### ISSUE TITLE
It is possible to register any Class as an OpMode

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#97]
Due to the use of reflection to store OpModes, trying to run a non-OpMode class as an OpMode throws some cryptic errors at runtime. It seems like this could be pretty easily solved by changing the method signature of `OpModeManager.register()` from `public void register(String name, Class opMode)` to `public void register(String name, Class<? extends OpMode> opMode)`.

**Comment by strugee** [comment]
@calebsander if you have the code to solve this (anything, really), you should consider sending a Pull Request!

**Comment by calebsander** [comment]
The issue is that the code is contained in one of the precompiled libraries, so it isn't really possible for the general public to submit pull requests until they decide to open-source the code.

**Comment by calebsander** [comment]
Still an issue in 2016.01.04

**Comment by calebsander** [comment]
Still an issue in yesterday's release

**Comment by calebsander** [comment]
I would recommend removing the class-based register method in favor of the instance-based method because it makes explicit when the constructor is called.

**Comment by magneticflux-** [comment]
Perhaps something similar to how the ```Runnable``` or ```Function<E, F>``` interfaces are used. On the other hand, that would complicate providing instances of them. A no-args constructor useable via reflection might be the best option, barring some sort of Java 8-esque ```Supplier<? extends OpMode>``` system.

**Comment by calebsander** [comment]
Fixed in 2.0.
